Csv secret
og-gluon/slim-auth pull request #8
Opened 2021-04-13 14:59 UTC by mrahbar

2021-04-13 15:44 UTC, janhicken approved these changes

2021-04-13 15:44 UTC, janhicken requested changes
Please document the changes in the README

2021-04-14 07:50 UTC, mrahbar commented
@janhicken is the version 1.1.4 for this release correct?

2021-04-14 09:04 UTC, janhicken commented
Yes :+1:

2021-04-14 09:05 UTC, janhicken approved these changes

2021-04-14 09:07 UTC, merged